### ISSUE TITLE
Better metric: # of lines?

### ISSUE THREAD

**Issue by jbaiter** [cneud/ocr-gt#1]
First of all, great work, thank you for putting together this list :-)

However, currently the only metric available in the comparison is the number of pages, which can be misleading. Archiscribe is listed with >3000 pages and e.g. the various IMPACT datasets with merely 50-200 pages. This makes it seem like the Archiscribe corpus is far bigger than it is: For each page, only one line was transcribed, while for IMPACT this was done for every line.
I think that, since for most OCR engines the line is the basis for training models, the comparison should reflect that.

**Comment by cneud** [comment]
Thx. This is basically just a small reminder since not all of these datasets are listed or in scope of [TC-11](http://datasets.iapr-tc11.org/). A GitHub table is also neither a flexible nor a useful way to maintain such info - I could imagine merging this into a section at [kba/awesome-ocr](https://github.com/kba/awesome-ocr) - which also has excellent exposure - sooner than later. 

About the choice of metric - mostly all other datasets then archiscribe and TCP (which are document-based TXT files) are usually cited by no. of pages since they stem from an era before the emergence of segmentation-free OCR engines. But I will try to highlight those differences for the time being without completely crashing the table layout and keep this open until the list has found a better home ;-)

**Comment by cneud** [comment]
One more thing: no. of lines is not known for the IMPACT datasets - and most others - it would be a good thing to determine and add this info!

**Comment by jbaiter** [comment]
Working on it :-)

**Comment by cneud** [comment]
`metric` can now be freely defined - at least until some form of json schema is drafted...
