### ISSUE TITLE
Make this a JSON file?

### ISSUE THREAD

**Issue by cneud** [cneud/ocr-gt#11]
Since the majority of the information contained here has now been merged into [kba/awesome-ocr](https://github.com/kba/awesome-ocr) and also due to the fact that Markdown tables are neither fun to edit nor specifically practical to reuse, I wonder: some information from here cannot easily be carried over to the awesome list without messing it up, but may still be relevant for some - would a JSON file make more sense perhaps? Or are there any other ideas, opinions on this? @kba @jbaiter

**Comment by kba** [comment]
I think that's an excellent idea. I would make it a YAML/HJSON/JSON5 file (because easier to read/edit) and define a JSON schema. This way, not only could we generate tables/lists but make the data machine-actionable in the long run, e.g. for an automated OCR training infrastructure.

Ideally such a data model should be developed to be congruous to the [upcoming schema for trained OCR models in OCR-D](https://github.com/OCR-D/spec/issues/86).

**Comment by cneud** [comment]
https://github.com/kba/awesome-ocr/issues/103

**Comment by cneud** [comment]
07ac8088bc60d4aaef2b4c1bd4f8270970c60af9

**Comment by cneud** [comment]
YAML looks good bcd027d190574805fc68087f5bcbbc18e08f2209
