### ISSUE TITLE
Generate web page for the YAML data?

### ISSUE THREAD

**Issue by kba** [cneud/ocr-gt#27]
This could be very simple, just a Jekyll page iterating through the entries in the YAML data and presenting them in a minimal HTML version at https://cneud.github.io/ocr-gt. It would even automatically rebuild for every change to the data. Or do you have another plan?

**Comment by cneud** [comment]
I don't wanna compete with http://datasets.iapr-tc11.org/ or the recently discovered https://htr-united.github.io/, but a simple static webpage was always intended. I've been looking at https://pmarsceill.github.io/just-the-docs/ since it includes a [search](https://pmarsceill.github.io/just-the-docs/docs/search/), but could probably use a hand setting up Jekyll with that.

**Comment by cneud** [comment]
Getting [there](https://cneud.github.io/ocr-gt/) :)
