### ISSUE TITLE
IMPACT github repo

### ISSUE THREAD

**Issue by amitdo** [cneud/ocr-gt#7]
@cneud,

* https://github.com/impactcentre/groundtruth-pol
* https://github.com/impactcentre/groundtruth-spa
* https://github.com/impactcentre/groundtruth-bhl

Would you like to add links to these repos?

I notices that you are the one who uploaded the data to these repos a few years ago :-)  

I assume that the first two are the same as the existing pol & spa data in your table.
Still, you can add them as alternative links.

**Comment by cneud** [comment]
Hi @amitdo,

Initially I thought these sets weren't too useful since - due to size issues - the corresponding images cannot be uploaded to GitHub. But I guess the GT files alone could still be useful to some (which I believe is what led me to the initial commit years ago), so I will think of a way to include these as alternative links for the PAGE files in the table. Thanks for reminding me!

**Comment by amitdo** [comment]
Consider using SourceForge as an alternative to all the 'need registration' open source data (impact, prima).
https://sourceforge.net/p/forge/documentation/Files/

**Comment by cneud** [comment]
Agreed that another hosting without any hazzle would be nice! SF could be an option, in fact we are currently looking at http://zenodo.org/ for this in the context of @OCR-D. I will see how far my connections with @impactcentre still go for organizing the deposit of the open IMPACT GT sets in such infrastructure.

**Comment by kba** [comment]
Sourceforge has become a bit shady in recent years. +1 for zenodo esp. since these are fixed and unchanging data sets.
